dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy2.7-5.9.0"
  - "pypy3.5-5.8.0"
  - "pypy3.5-5.9.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=slack setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: jk2xD3tclhGxmoPcHY1ukLidAYw6MlVL5NmztDQjrv9S+ILJ7q0b9iu9+8kYSpzPlbV/OHg7NGthbFTaxJcfAlz+K/CEQ6wX5V5J+RmT02AH2FlHuSKsK/CXmzR6SnXNlppbcCDB1sCSLertmlYZd29ZBEV3E3d/1+uG2/NtHRKGvWopriEmuUMo8XL1WRYhBxRmP470hrptLGMka7zRE5t3m7V5XQEgxp81rm7D/NOavbxR+YKBV2j7vRyH4gSzToqrn+fJmT587MVm3G9tePI1KeZGj/9Yy/pvGaAIiVZwsoSPFeIclTsRBtazv74rplifUWFq2aw7sbLG9p8WADxS8uMAfMwz8TUEHrHM8IdZ+b1lSxUXtRlM9b2pmetqKtH5oZZnigUqPGysNJemhJt43cSgVFIw+9Bri9RzSy+qvfMcPbC1JA6Af2ifcPYNEHBZR4f7OQgRBFEQ6wb7S9gl9GYFESPjzdp62s5mJE+GIV6PapHHXuwkvSnydYL+FhqbqEkF3vQqm8xALowhpWEXAMpCz6tdIGo7Yt8LWw3iG7UDgXSAXT0zCoJ1s9IjxQTLa/mq6qPqN7agjEyfh5VdRkgNWOcDuMX65YFngGolKpLpcgNUTSpvz7qP1oxt/U0ocFibxdlTDd+Ize+t+emp5mmdihoYH4zeIQaA53w=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
